name: Builds of PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache Loom Files
        uses: actions/cache@v2
        with:
          path: |
            build/loom-cache
            .gradle/loom-cache
          key: ${{ runner.os }}-loom-${{ hashFiles('**/*gradle*', '**/*.accesswidener') }}
          restore-keys: |
            ${{ runner.os }}-loom-
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Upload Main JARs
        uses: actions/upload-artifact@v2.2.0
        with:
          name: quickcarpet-jars
          path: build/libs/*.jar
      - name: Upload API JARs
        uses: actions/upload-artifact@v2.2.0
        with:
          name: quickcarpet-api-jars
          path: api/build/libs/*.jar
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.9
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: build/test-results/**/*.xml